## LOGGING
#logging:
#  level:
#    org.springframework.web: DEBUG
#
#
#  # APPLICATION
#spring:
#  application:
#    name: turkcell-customer-updater-poc
#  # MONGODB
#  data:
#    mongodb:
#      authentication-database: admin
#      database: ${MONGO_DB_NAME}
#      host: ${MONGO_HOST}
#      port: ${MONGO_PORT}
#      username: ${MONGO_USERNAME}
#      password: ${MONGO_PASSWORD}
#
#
#kafka-client-id: customerupdaterclient
#kafka-bootstrap-servers: ${KAFKA_URL}
#kafka-producer-key-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
#kafka-producer-value-serializer: org.apache.kafka.common.serialization.StringSerializer
#
#kafka-customer-topic: customerupdater
#
#server:
#  port: 8054
#  servlet:
#    context-path: /customer-updater


# LOGGING
logging:
  level:
    org.springframework.web: DEBUG


  # APPLICATION
spring:
  application:
    name: turkcell-customer-updater-poc
  # MONGODB
  data:
    mongodb:
      authentication-database: admin
      database: turkcell-customer-updater
      host: localhost
      port: 27017
      username: admin
      password: pass


kafka-client-id: customerupdaterclient
kafka-bootstrap-servers: 165.22.22.133:31847
#kafka-bootstrap-servers: 207.154.232.181:31357
kafka-producer-key-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
kafka-producer-value-serializer: org.apache.kafka.common.serialization.StringSerializer

kafka-customer-topic: customerupdater

server:
  port: 8054
  servlet:
    context-path: /customer-updater
