# LOGGING
logging:
  level:
   org.springframework.web: DEBUG


  # APPLICATION
spring:
  application:
   name: turkcell-customer-updater-poc
  # MONGODB
  data:
     mongodb:
       authentication-database: admin
       database: turkcell-customer-updater
       host: 165.22.22.133
       port: 31786
       username: root
       password: kafein2020!...


kafka-client-id: customerupdaterclient
kafka-bootstrap-servers: 165.22.22.133:31847
#kafka-bootstrap-servers: 207.154.232.181:31357
kafka-producer-key-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
kafka-producer-value-serializer: org.apache.kafka.common.serialization.StringSerializer

kafka-customer-topic: customerupdater

server:
  port: 8080
  servlet:
    context-path: /customer-updater
