# LOGGING
logging:
  level:
    org.springframework.web: DEBUG


  # APPLICATION
spring:
  application:
    name: turkcell-customer-updater-poc
  # MONGODB
  data:
    mongodb:
      authentication-database: admin
      database: ${MONGO_DB_NAME}
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}


kafka-client-id: customerupdaterclient
kafka-bootstrap-servers: ${KAFKA_URL}
kafka-producer-key-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
kafka-producer-value-serializer: org.apache.kafka.common.serialization.StringSerializer

kafka-customer-topic: ${KAFKA_CUSTOMER_TOPIC}

server:
  port: 8054
  servlet:
    context-path: /customer-updater
